### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by Princegupta101** [subhadeeproy3902/BloxAI#5]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by vanshikab52** [comment]
A Code_Of_Conduct.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions. It sets clear guidelines for expected behavior and helps ensure that all contributors feel safe and respected.
The repository currently lacks a CODE_OF_CONDUCT.md file which is an important resource for fostering a welcoming and inclusive environment within our community.
@subhadeeproy3902  You can assign this issue to me as I'm working under GSSoC'24 as a contributor. I can add a code of conduct to this project.
Thanks

**Comment by subhadeeproy3902** [comment]
Go ahead @Princegupta101 @vanshikab52
